name: Build & run tests

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-18.04
          - ubuntu-20.04
          - macos-10.15 # catalina
          - macos-11.0  # big sur
          - windows-2016
          - windows-2019
        config:
          - Release
        include:
          - os: windows-2016
            cmake-generator: -G "Visual Studio 15 2017" -A x64
          - os: windows-2019
            cmake-generator: -G "Visual Studio 16 2019" -A x64

    steps:
      - uses: actions/checkout@v2

      - if: contains(matrix.os, 'ubuntu')
        name: deps
        run: |
          sudo apt update
          sudo apt-get install libasound2-dev xorg-dev libglu1-mesa-dev

      - name: configure
        run: mkdir build && cd build && cmake -DASSETS=ON cmake ${{ matrix.cmake-generator }} ..

      - name: build
        run: cmake --build build --target extempore --config ${{ matrix.config }}

      - name: aot-compile-stdlib
        run: cmake --build build --config ${{ matrix.config }}

      - name: test
        run: cd build && ctest --build-config ${{ matrix.config }} --label-regex libs-core
