name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*" # Push events to matching vX.X.X*, e.g. v0.9.8-beta

jobs:
  build:
    name: build & upload the zipfile to the GitHub releases page
    runs-on: ${{ matrix.os }}
    timeout-minutes: 180
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-18.04
          - ubuntu-20.04
          - macos-10.15 # catalina
          - macos-11.0  # big sur
          - windows-2016
          - windows-2019
        include:
          - os: windows-2016
            cmake-generator: -G "Visual Studio 15 2017" -A x64
          - os: windows-2019
            cmake-generator: -G "Visual Studio 16 2019" -A x64

    steps:
      - uses: actions/checkout@v2

      - if: contains(matrix.os, 'ubuntu')
        name: deps
        run: |
          sudo apt update
          sudo apt-get install libasound2-dev xorg-dev libglu1-mesa-dev

      - name: configure
        run: mkdir build && cd build && cmake ${{ matrix.cmake-generator }} -DPACKAGE=ON ..

      - name: build
        run: cmake --build build --config Release --target package

      - id: tag-name
        name: get git tag name
        uses: olegtarasov/get-tag@v2.1

      - name: upload zipfile to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.EXTEMPORE_RELEASE_TOKEN }}
          file: build/extempore.zip
          asset_name: extempore-${{ steps.tag-name.outputs.tag }}-${{ matrix.os }}.zip
          tag: ${{ github.ref }}
          overwrite: true
